[package]
name = "libdownloader"
version = "0.0.1"
authors = ["Samuel Marks <@SamuelMarks>"]
license = 'Apache-2.0 OR MIT'
edition = "2018"

[dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
http = "0.2.1"
lazy_static = "1.4.0"
surf = "1.0.3"
